# Generated by Django 6.0.3 on 2026-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('district', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('temple', 'Temple'), ('church', 'Church'), ('fort', 'Fort'), ('palace', 'Palace'), ('museum', 'Museum'), ('nature', 'Nature'), ('hill', 'Hill/Lake')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('is_crowded', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
