# Generated by Django 6.0.3 on 2026-03-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_theme',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
